AllCops:
  TargetRubyVersion: 2.6
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  DisabledByDefault: true
  Exclude:
    - "**/templates/**/*"
    - "**/vendor/**/*"
    - "actionpack/lib/action_dispatch/journey/parser.rb"
    - "railties/test/fixtures/tmp/**/*"
    - "actionmailbox/test/dummy/**/*"
    - "actiontext/test/dummy/**/*"
    - "**/node_modules/**/*"
    # Additional exclude files by rubocop-rails_config
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"

Performance:
  Exclude:
    - "**/spec/**/*"
