AllCops:
  TargetRubyVersion: 2.6
inherit_gem:
  rubocop-rails_config:
    - config/rails.yml
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
