AllCops:
  TargetRubyVersion: 2.6
inherit_from: ./rails_cop.yml
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
