language: ruby
rvm:
  - 2.2
  - jruby
  - truffleruby
  - 2.0.0-p247
addons:
  postgresql: '9.6'
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
dist: trusty
language: ruby
rvm:
  - 2.6.3
script:
  - bundle install
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT